name: Auto-assign

on:
  issues:
    types: [moved]

jobs:
  assign-on-status-change:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ secrets.GH_PROJECT_PAT }}
      PROJECT_ID: "PVT_kwHOAnbWOs4A9S3k"
      STATUS_FIELD_ID: "PVTSSF_lAHOAnbWOs4A9S3kzgxCfsA"
      READY_OPTION_ID: "f75ad846"
      IN_PROGRESS_OPTION_ID: "47fc9ee4"

    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GH_TOKEN }}
          script: |
            const issueId = context.payload.issue.node_id;
            const actorId = (await github.graphql(`query { viewer { id } }`)).viewer.id;

            const res = await github.graphql(`
              query ($projectId: ID!, $issueId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    items(first: 100, query: "") {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            id
                            number
                          }
                        }
                        fieldValues(first: 20) {
                          nodes {
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              field {
                                id
                              }
                              optionId
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }`, {
                projectId: process.env.PROJECT_ID,
                issueId
              });

            const item = res.node.items.nodes.find(i => i.content?.id === issueId);
            if (!item) return;

            const statusField = item.fieldValues.nodes.find(f => f.field.id === process.env.STATUS_FIELD_ID);
            const previousStatus = statusField?.optionId;

            if (previousStatus === process.env.READY_OPTION_ID) {
              // Assign actor
              await github.rest.issues.addAssignees({
                ...context.repo,
                issue_number: context.issue.number,
                assignees: [context.actor]
              });
            }
